#PRINTO DCOMPOSE

version: "3.8"

volumes:
  rabbitmq_data:

services:

  ###################################
  # Provider: provider microservice
  ###################################
  provider:
    build:
      context: ./container-create_provider/
      dockerfile: provider.dockerfile
    image: jinloh/provider:printo
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/provider
      PYTHONUNBUFFERED: 1
    ports:
      - "5007:5007"

  ###################################
  # Google Maps: google_maps microservice
  ###################################
  google_maps:
    build:
      context: ./container-create_provider/
      dockerfile: google_maps.dockerfile
    image: jinloh/google_maps:printo
    restart: always
    environment:
      PYTHONUNBUFFERED: 1
    ports:
      - "5002:5002"

  ###############################################
  # Create Provider: create_provider complex microservice
  ###############################################
  create_provider:
    build:
      context: ./container-create_provider/
      dockerfile: create_provider.dockerfile
    image: jinloh/create_provider:printo
    restart: always
    depends_on:
      - provider
      - google_maps
    environment:
      provider_URL: http://provider:5007/provider
      google_maps_URL: http://google_maps:5002/get_current_location
      PYTHONUNBUFFERED: 1
    ports:
      - "5006:5006"

  ###################################
  # Request: Request microservice
  ###################################
  request:
    build:
      context: ./container-create_request/
      dockerfile: request.dockerfile
    image: jinloh/request:printo
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/request
      PYTHONUNBUFFERED: 1
    ports:
      - "5003:5003"

  ###################################
  # Gdrive: GoogleDrive microservice
  ###################################

  google_drive:
    build:
      context: ./container-create_request/container-gdrive/
      dockerfile: app.dockerfile
    image: jinloh/gdrive:printo
    restart: always
    environment:
      #dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/request
      PYTHONUNBUFFERED: 1
    ports:
      - "3000:3000"

 ###############################################
  # Create Request: Create a Request COMPLEX microservice
  ###############################################
  create_request:
    build:
      context: ./container-create_request/
      dockerfile: create_request.dockerfile
    image: jinloh/create_request:printo
    restart: always
    #networks:
    #  - kong-net
    depends_on:
      - request
      - google_maps
      - google_drive
    environment:
      request_URL : "http://request:5003/insert_request"
      update_location_URL : "http://request:5003/update_location/"
      update_gdrive_URL : "http://request:5003/update_document_id/"
      googleDrive_URL : "http://google_drive:3000/insert_document"
      googleMaps_URL : "http://google_maps:5002/get_current_location"
      print_details_URL : "http://request:5003/update_print_details/"
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"